version: '3.8'

services:
  backend:
    image: php:7.4-fpm
    ports:
      - 9000:9000
    volumes:
      - ./mounts/site:/var/www/html
    networks:
      - internal
  frontend:
    image: nginx:1.23-alpine
    volumes:
      - ./mounts/site:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on: 
      - backend
    networks:
      - internal

networks:
  internal: {}